# Place these:
# num_envs: number of training environments to run
# render: whether or not to render
# dump_frequency: frequency of dumps
# write_goal_dumps: whether to write goals in dumps
# write_full_episode_dumps: whether to write full episode dumps

display:
  customStats: null
  gameStats: true
  renderResolution: 1280

dump:
  fullEpisodes: false
  scores: false

players:
  - kind: agent
    side: left
    count: 11
  - kind: bot
    side: right
    count: 1

game:
  actionSet: full
  level: 11_vs_11_stochastic
  physicsStepsPerFrame: 10
  realTime: false

env:
  core: party

video:
  format: avi
  quality: 0    # 0 - low, 1 - medium, 2 - high
  write: false

tracesDir: /tmp/dumps
